-- MySQL Script generated by MySQL Workbench
-- Wed Oct  3 20:00:56 2018
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema federacao_tenis
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema federacao_tenis
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `federacao_tenis` DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci ;
USE `federacao_tenis` ;

-- -----------------------------------------------------
-- Table `federacao_tenis`.`categorias`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `federacao_tenis`.`categorias` ;

CREATE TABLE IF NOT EXISTS `federacao_tenis`.`categorias` (
  `id` INT NOT NULL AUTO_INCREMENT COMMENT '',
  `nome` VARCHAR(45) NOT NULL COMMENT '',
  PRIMARY KEY (`id`)  COMMENT '')
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `federacao_tenis`.`tenistas`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `federacao_tenis`.`tenistas` ;

CREATE TABLE IF NOT EXISTS `federacao_tenis`.`tenistas` (
  `id` INT NOT NULL AUTO_INCREMENT COMMENT '',
  `nome` VARCHAR(150) NOT NULL COMMENT '',
  `data_nascimento` DATETIME NOT NULL COMMENT '',
  `sexo` BIT NOT NULL COMMENT '',
  `categorias_id` INT NOT NULL COMMENT '',
  PRIMARY KEY (`id`)  COMMENT '',
  INDEX `fk_tenistas_categorias1_idx` (`categorias_id` ASC)  COMMENT '',
  CONSTRAINT `fk_tenistas_categorias1`
    FOREIGN KEY (`categorias_id`)
    REFERENCES `federacao_tenis`.`categorias` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `federacao_tenis`.`campeonatos`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `federacao_tenis`.`campeonatos` ;

CREATE TABLE IF NOT EXISTS `federacao_tenis`.`campeonatos` (
  `id` INT NOT NULL AUTO_INCREMENT COMMENT '',
  `nome` VARCHAR(150) NOT NULL COMMENT '',
  `edicao` VARCHAR(45) NULL COMMENT '',
  `data_realizacao` DATETIME NOT NULL COMMENT '',
  `premiacao` DECIMAL(10,2) NOT NULL COMMENT '',
  PRIMARY KEY (`id`)  COMMENT '')
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `federacao_tenis`.`jogos`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `federacao_tenis`.`jogos` ;

CREATE TABLE IF NOT EXISTS `federacao_tenis`.`jogos` (
  `tenista_01_id` INT NOT NULL COMMENT '',
  `tenista_02_id` INT NOT NULL COMMENT '',
  `campeonatos_id` INT NOT NULL COMMENT '',
  `publico` INT NOT NULL COMMENT '',
  `pontuacao_tenista_01` INT NOT NULL COMMENT '',
  `pontuacao_tenista_02` INT NOT NULL COMMENT '',
  `quadras_id` INT NOT NULL COMMENT '',
  PRIMARY KEY (`tenista_01_id`, `tenista_02_id`, `campeonatos_id`)  COMMENT '',
  INDEX `fk_sets_tenistas1_idx` (`tenista_01_id` ASC)  COMMENT '',
  INDEX `fk_sets_tenistas2_idx` (`tenista_02_id` ASC)  COMMENT '',
  INDEX `fk_jogos_campeonatos1_idx` (`campeonatos_id` ASC)  COMMENT '',
  INDEX `fk_jogos_quadras1_idx` (`quadras_id` ASC)  COMMENT '',
  CONSTRAINT `fk_sets_tenistas1`
    FOREIGN KEY (`tenista_01_id`)
    REFERENCES `federacao_tenis`.`tenistas` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_sets_tenistas2`
    FOREIGN KEY (`tenista_02_id`)
    REFERENCES `federacao_tenis`.`tenistas` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_jogos_campeonatos1`
    FOREIGN KEY (`campeonatos_id`)
    REFERENCES `federacao_tenis`.`campeonatos` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_jogos_quadras1`
    FOREIGN KEY (`quadras_id`)
    REFERENCES `federacao_tenis`.`quadras` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `federacao_tenis`.`quadras`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `federacao_tenis`.`quadras` ;

CREATE TABLE IF NOT EXISTS `federacao_tenis`.`quadras` (
  `id` INT NOT NULL AUTO_INCREMENT COMMENT '',
  `tipo` VARCHAR(45) NOT NULL COMMENT '',
  `endereco` VARCHAR(45) NOT NULL DEFAULT 'Brasil' COMMENT '',
  PRIMARY KEY (`id`)  COMMENT '')
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `federacao_tenis`.`jogos`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `federacao_tenis`.`jogos` ;

CREATE TABLE IF NOT EXISTS `federacao_tenis`.`jogos` (
  `tenista_01_id` INT NOT NULL COMMENT '',
  `tenista_02_id` INT NOT NULL COMMENT '',
  `campeonatos_id` INT NOT NULL COMMENT '',
  `publico` INT NOT NULL COMMENT '',
  `pontuacao_tenista_01` INT NOT NULL COMMENT '',
  `pontuacao_tenista_02` INT NOT NULL COMMENT '',
  `quadras_id` INT NOT NULL COMMENT '',
  PRIMARY KEY (`tenista_01_id`, `tenista_02_id`, `campeonatos_id`)  COMMENT '',
  INDEX `fk_sets_tenistas1_idx` (`tenista_01_id` ASC)  COMMENT '',
  INDEX `fk_sets_tenistas2_idx` (`tenista_02_id` ASC)  COMMENT '',
  INDEX `fk_jogos_campeonatos1_idx` (`campeonatos_id` ASC)  COMMENT '',
  INDEX `fk_jogos_quadras1_idx` (`quadras_id` ASC)  COMMENT '',
  CONSTRAINT `fk_sets_tenistas1`
    FOREIGN KEY (`tenista_01_id`)
    REFERENCES `federacao_tenis`.`tenistas` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_sets_tenistas2`
    FOREIGN KEY (`tenista_02_id`)
    REFERENCES `federacao_tenis`.`tenistas` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_jogos_campeonatos1`
    FOREIGN KEY (`campeonatos_id`)
    REFERENCES `federacao_tenis`.`campeonatos` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_jogos_quadras1`
    FOREIGN KEY (`quadras_id`)
    REFERENCES `federacao_tenis`.`quadras` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
